### ISSUE TITLE
Running

### ISSUE THREAD

**Issue by rollymom** [nlj-guang/quantize_cnn#1]
Hello 
I wanted to test quantization, i was so appreciated to find your code  
But, As i couldn`t read chineese, It was a little difficult to understand meaning of parameters
 Could you tell me how to run this code? 

I got this error, and how i can handle this?
and actually i don`t know what is the role of the line  

----------------------------------------------------------------------
    path = './cifar_net.pth' //i change h.path to path
    act_path = os.path.join(path, 'temp', name+'_'+data_set+'_act', name+'_act.pth.tar')
    init_model = torch.load(act_path)
    model.load_state_dict(init_model['state_dict'])
---------------------------------------------------------------------------
$ python3 train.py --save-dir ./result

=> init_lr      0.001               
=> lr-step      6                   
=> momentum     0.9                 
=> weight-decay 0.0001              
=> batch-size   128                 
=> balance      100                 
=> save-dir     ./result            

Traceback (most recent call last):
  File "train.py", line 151, in <module>
    main()
  File "train.py", line 86, in main
    init_model = torch.load(act_path)
  File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 215, in __init__
    super(_open_file, self).__init__(open(name, mode))
NotADirectoryError: [Errno 20] Not a directory: './cifar_net.pth/temp/vgg16_cifar10_act/vgg16_act.pth.tar'

**Comment by nlj-guang** [comment]
Hello:
Thanks for your questions.
The mean of the four code lines is load these parameter into model.
The error is that you lack for these parameter.
You can try the original model and original parameter.


What's more, can you tell me where are you from?
my English is very terrible.
 
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "nlj-guang/quantize_cnn"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月24日(星期四) 晚上6:39
收件人:&nbsp;"nlj-guang/quantize_cnn"<quantize_cnn@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[nlj-guang/quantize_cnn] Running (#1)





 
Hello
 I wanted to test quantization, i was so appreciated to find your code
 But, As i couldn`t read chineese, It was a little difficult to understand meaning of parameters
 Could you tell me how to run this code?
 
I got this error, and how i can handle this?
 and actually i don`t know what is the role of the line
 
 path = './cifar_net.pth' //i change h.path to path act_path = os.path.join(path, 'temp', name+'_'+data_set+'_act', name+'_act.pth.tar') init_model = torch.load(act_path) model.load_state_dict(init_model['state_dict'])  
 
$ python3 train.py --save-dir ./result
 
=&gt; init_lr      0.001
 =&gt; lr-step      6
 =&gt; momentum     0.9
 =&gt; weight-decay 0.0001
 =&gt; batch-size   128
 =&gt; balance      100
 =&gt; save-dir     ./result
 
Traceback (most recent call last):
 File "train.py", line 151, in 
 main()
 File "train.py", line 86, in main
 init_model = torch.load(act_path)
 File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 584, in load
 with _open_file_like(f, 'rb') as opened_file:
 File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 234, in _open_file_like
 return _open_file(name_or_buffer, mode)
 File "/home/sr2/so0.bak/venv/venv/lib/python3.7/site-packages/torch/serialization.py", line 215, in init
 super(_open_file, self).init(open(name, mode))
 NotADirectoryError: [Errno 20] Not a directory: './cifar_net.pth/temp/vgg16_cifar10_act/vgg16_act.pth.tar'
